// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Lexicon.Account {
	
	
	public partial class ChangePassword {
		
		protected System.Web.UI.WebControls.Content HeaderContent;
		
		protected System.Web.UI.WebControls.Content BodyContent;
		
		protected System.Web.UI.WebControls.ChangePassword ChangeUserPassword;
		
		protected System.Web.UI.WebControls.Literal FailureText;
		
		protected System.Web.UI.WebControls.ValidationSummary ChangeUserPasswordValidationSummary;
		
		protected System.Web.UI.WebControls.Label CurrentPasswordLabel;
		
		protected System.Web.UI.WebControls.TextBox CurrentPassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator CurrentPasswordRequired;
		
		protected System.Web.UI.WebControls.Label NewPasswordLabel;
		
		protected System.Web.UI.WebControls.TextBox NewPassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator NewPasswordRequired;
		
		protected System.Web.UI.WebControls.Label ConfirmNewPasswordLabel;
		
		protected System.Web.UI.WebControls.TextBox ConfirmNewPassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator ConfirmNewPasswordRequired;
		
		protected System.Web.UI.WebControls.CompareValidator NewPasswordCompare;
		
		protected System.Web.UI.WebControls.Button CancelPushButton;
		
		protected System.Web.UI.WebControls.Button ChangePasswordPushButton;
	}
}
