// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Lexicon.Account {
	
	
	public partial class Login {
		
		protected System.Web.UI.WebControls.Content HeaderContent;
		
		protected System.Web.UI.WebControls.Content BodyContent;
		
		protected System.Web.UI.WebControls.HyperLink RegisterHyperLink;
		
		protected System.Web.UI.WebControls.Login LoginUser;
		
		protected System.Web.UI.WebControls.Literal FailureText;
		
		protected System.Web.UI.WebControls.ValidationSummary LoginUserValidationSummary;
		
		protected System.Web.UI.WebControls.Label UserNameLabel;
		
		protected System.Web.UI.WebControls.TextBox UserName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator UserNameRequired;
		
		protected System.Web.UI.WebControls.Label PasswordLabel;
		
		protected System.Web.UI.WebControls.TextBox Password;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator PasswordRequired;
		
		protected System.Web.UI.WebControls.CheckBox RememberMe;
		
		protected System.Web.UI.WebControls.Label RememberMeLabel;
		
		protected System.Web.UI.WebControls.Button LoginButton;
	}
}
