// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Lexicon.Account {
	
	
	public partial class Register {
		
		protected System.Web.UI.WebControls.Content HeaderContent;
		
		protected System.Web.UI.WebControls.Content BodyContent;
		
		protected System.Web.UI.WebControls.CreateUserWizard RegisterUser;
		
		protected System.Web.UI.WebControls.PlaceHolder wizardStepPlaceholder;
		
		protected System.Web.UI.WebControls.PlaceHolder navigationPlaceholder;
		
		protected System.Web.UI.WebControls.CreateUserWizardStep RegisterUserWizardStep;
		
		protected System.Web.UI.WebControls.Literal ErrorMessage;
		
		protected System.Web.UI.WebControls.ValidationSummary RegisterUserValidationSummary;
		
		protected System.Web.UI.WebControls.Label UserNameLabel;
		
		protected System.Web.UI.WebControls.TextBox UserName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator UserNameRequired;
		
		protected System.Web.UI.WebControls.Label EmailLabel;
		
		protected System.Web.UI.WebControls.TextBox Email;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator EmailRequired;
		
		protected System.Web.UI.WebControls.Label PasswordLabel;
		
		protected System.Web.UI.WebControls.TextBox Password;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator PasswordRequired;
		
		protected System.Web.UI.WebControls.Label ConfirmPasswordLabel;
		
		protected System.Web.UI.WebControls.TextBox ConfirmPassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator ConfirmPasswordRequired;
		
		protected System.Web.UI.WebControls.CompareValidator PasswordCompare;
		
		protected System.Web.UI.WebControls.Button CreateUserButton;
	}
}
