// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Lexicon {
	
	
	public partial class WebForm1 {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList2;
		
		protected System.Web.UI.WebControls.TextBox SearchTextBox1;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList1;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.WebControls.GridView GridView1;
		
		protected System.Web.UI.WebControls.TextBox TextBox1;
		
		protected System.Web.UI.WebControls.HyperLink Label1;
		
		protected System.Web.UI.WebControls.AccessDataSource AccessDataSource1;
	}
}
